package com.tns.cg.smms.services;

import java.util.List;

import javax.transaction.Transactional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.tns.cg.smms.entities.Shop;
import com.tns.cg.smms.repositories.ShopRepository;

@Service
@Transactional
public class ShopService {
	@Autowired
	// This means to get the bean which is auto-generated by Spring
	// We will use it to handle the data
	ShopRepository Repo;

	// Retreiving all Shops
	public List<Shop> getAllShops(){
		return Repo.findAll();
	}
	
	// Creating New Shop
	public void save(Shop emp) {
	 Repo.save(emp);
	}
	
	//  Retreiving shop by id
	public Shop getShopById(Integer id) {
		return Repo.findById(id).get();
	}
	
	// Deleting shop from database
	public void delete(Integer id) {
		Repo.deleteById(id);
	}
}
